service: sms-mobimind

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: sms_mobimind
    handler: lambda.handler
    description: class file for invoke function and deploy using github action
    timeout: 10 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"